Chat.Api/Controllers/BlobSharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Chat.Api.Controllers
{
    public class BlobSharedController : Controller
    {
        // GET: BlobShared
        public ActionResult Index()
        {
            return View();
        }
    }
}

Chat.Api/Controllers/BoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Chat.Api.Controllers
{
    public class BoardController : Controller
    {
        // GET: Board
        public ActionResult Index()
        {
            return View();
        }
    }
}

Chat.Api/Controllers/CamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Chat.Api.Controllers
{
    public class CamController : Controller
    {
        // GET: Cam
        public ActionResult Index()
        {
            return View();
        }
    }
}

Chat.Api/Controllers/CamLiveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Chat.Api.Controllers
{
    public class CamLiveController : Controller
    {
        // GET: CamLive
        public ActionResult Index()
        {
            return View();
        }
    }
}

Chat.Api/Controllers/ChatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Chat.Api.Controllers
{
    public class ChatController : Controller
    {
        // GET: Chat
        public ActionResult Index()
        {
            return View();
        }
    }
}

Chat.Api/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Chat.Api.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";

            return View();
        }
    }
}

Chat.Api/Controllers/LuisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Chat.Api.Controllers
{
    public class LuisController : Controller
    {
        // GET: Luis
        public ActionResult Index()
        {
            return View();
        }
    }
}

Chat.Api/Controllers/StreamingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Chat.Api.Controllers
{
    public class StreamingController : Controller
    {
        // GET: Streaming
        public ActionResult Index()
        {
            return View();
        }
    }
}

Chat.Api/Controllers/ValuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace Chat.Api.Controllers
{
    public class ValuesController : ApiController
    {
        // GET api/values
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/values/5
        public string Get(int id)
        {
            return "value";
        }

        // POST api/values
        public void Post([FromBody]string value)
        {
        }

        // PUT api/values/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/values/5
        public void Delete(int id)
        {
        }
    }
}

Chat.Api/Views/BlobShared/index.cshtml
<div class="panel panel-body">
    <div class="row">
        <div class="col-md-12">
            <div style="margin: 0 auto;width: 30%;">
                <button id="play" class="btn btn-block btn-success" style="margin: 2% 0;">Iniciar</button>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <video id="video" style="width:100%;height:500px;border: 1px solid;margin: 1% 0;" controls></video>
        </div>
    </div>
</div>

<script>
    var video = document.querySelector('video');

    var btnStart = document.getElementById("play");

    btnStart.addEventListener('click', videoStart);

    function videoStart() {
        var errBack = function (e) {
            alert('Opps.. no se puede utilizar la cámara' + e, e);
        };

        var constraints = {
            video:true,
            audio: false
        };

        if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
            navigator.mediaDevices.getUserMedia(constraints).then(function (stream) {
                video.src = window.URL.createObjectURL(stream);
                console.log(window.URL.createObjectURL(stream));
                video.play();
                localStream = stream;
            }, errBack);
        }
        else if (navigator.getUserMedia) { // Standard
            navigator.getUserMedia(constraints, function (stream) {
                video.src = window.URL.createObjectURL(stream);
                video.play();
                localStream = stream;
            }, errBack);
        } else if (navigator.webkitGetUserMedia) { // WebKit-prefixed
            navigator.webkitGetUserMedia(constraints, function (stream) {
                video.src = window.URL.createObjectURL(stream);
                video.play();
                localStream = stream;
            }, errBack);
        } else if (navigator.mozGetUserMedia) { // Mozilla-prefixed
            navigator.mozGetUserMedia(constraints, function (stream) {
                video.src = window.URL.createObjectURL(stream);
                video.play();
                localStream = stream;
            }, errBack);
        }
    }
</script>

Chat.Api/Views/Board/index.cshtml
<div style="margin:1% auto;width:50%">
    <div class="col-md-6 form-group">
        <button id="reset" class="btn btn-success btn-block" style="float:left;">Limpiar</button>
    </div>
    <div class="col-md-6 form-group">
        <button id="resetImg" class="btn btn-success btn-block" style="float:left;">Borrar Todo</button>
    </div>
</div>
<div style="margin:auto;width:10%">
    <div class="form-group">
        <label for="file-input" style="width:100%;">
            <img src="http://goo.gl/pB9rpQ" width="80" style="display:block; margin:0 auto;cursor:pointer" />
        </label>

        <input type="file" id="file-input" onchange="previewFile(this)" style="display:none;" multiple/>
    </div>
</div>

<div id="canvas-container">
    <canvas class="board" width="700" height="500" id="canvas">Su navegador no soporta canvas :( </canvas>
</div>


<script src="~/Scripts/board.js"></script>

Chat.Api/Views/Cam/index.cshtml
<div class="panel panel-body">
    <div class="row">
        <div class="col-md-12">
            <select id="sVideo" style="display: block; margin:0 auto"></select>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-4">
                <button id="play" class="btn btn-block btn-success" style="margin: 2% 0;">Iniciar</button>
            </div>
            <div class="col-md-4">
                <button id="screenShot" class="btn btn-block btn-info" style="margin: 2% 0;">Capturar</button>
            </div>
            <div class="col-md-4">
                <button id="stop" class="btn btn-block btn-danger" style="margin: 2% 0;">Detener</button>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <video id="video" style="width:100%;height:500px;border: 1px solid;margin: 1% 0;"></video>
        </div>
        <div class="col-md-6">
            <img src="" style="min-width:100%; width:100%; min-height:500px;border: 1px solid;margin: 1% 0;">
            <canvas id="canvas" width="640" height="480" style="display:none;"></canvas>
        </div>
    </div>
</div>

<script src="~/Scripts/Cam.js"></script>

Chat.Api/Views/CamLive/index.cshtml
<div class="panel panel-body">
    <div class="row">
        <div class="col-md-12">
            <select id="sVideo" style="display: block; margin:0 auto"></select>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-6">
                <button id="play" class="btn btn-block btn-success" style="margin: 2% 0;">Iniciar</button>
            </div>
            <div class="col-md-6">
                <button id="stop" class="btn btn-block btn-danger" style="margin: 2% 0;">Detener</button>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <video id="video" style="width:100%;height:500px;border: 1px solid;margin: 1% 0;"></video>
        </div>
        <div class="col-md-6">
            @*<img src="" style="min-width:100%; width:100%; min-height:500px;border: 1px solid;margin: 1% 0;">*@
            <canvas id="canvas" width="640" height="480" style="border: 1px solid;margin: 1% 0;"></canvas>
        </div>
    </div>
</div>

<script src="~/Scripts/CamLive.js"></script>

Chat.Api/Views/Chat/index.cshtml
@{
    ViewBag.Title = "Chat Server";
}

<div class="container">
    <div class="row">
        <h1 class="col-xs-12" id="who_is">Who are you?</h1>
    </div>

    <input type="hidden" id="displayname" />
    <br />
    <div class="row">
        <div class="col-xs-12 col-lg-12" id="onlineUsers">

        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <input type="text" id="chat-input" placeholder="To chat, type here and press Enter!" class="form-control" />
            <hr />
            <div id="chat-window">

            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
        $(function () {
            // Declare a proxy to reference the hub.
            var chat = $.connection.chat;

            chat.client.showUsersOnLine = function (data) {

                var content = "<table class='table table-resposive table-stripped'><th>Connection ID</th><th>Alias connected</th>";
                $("#onlineUsers").html("");

                $.each(data, function (k, v) {
                    content += "<tr><td>" + v.UserConnecionId + "</td><td>" + v.UserName + "</td></tr>";
                });
                content += "</table>"
                $("#onlineUsers").append(content);
            };

            var chatInput = $("#chat-input");
            var chatWindow = $("#chat-window");
            var userName;

            //this is the function that's run when the "messageReceived" function is called from the server
            chat.client.MessageReceived = function (username, message) {
                chatWindow.append("<div><strong>" + username + ": </strong>" + message + "</div>");
            };

            //ask for a username
            setTimeout(function () {
                userName = prompt("Please enter a username.");
                // Get the user name and store it to prepend to messages.
                $('#displayname').val(userName);
                $("#who_is").html($('#displayname').val());
                $.connection.hub.qs = "userMail=" + $('#displayname').val();
                // Set initial focus to message input box.
                $('#message').focus();
            }, 0);

           
            // Start the connection.
            $.connection.hub.start().done(function () {
                chatInput.keydown(function (e) {

                    if (e.which === 13) {
                        var text = chatInput.val();

                        //empty the textbox
                        chatInput.val("");

                        //send the message to the server
                        chat.server.sendMessage(userName, text);

                        //focus cursor on the textbox for easy chatting!
                        self.focus();
                    }
                });
            });
        });
</script>

Chat.Api/Views/Home/Index.cshtml
<div id="main_Menu" class="modal" role="dialog" data-backdrop="static">
    <div class="modal-dialog">

        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Dummie SignarlR Manager</h4>
            </div>
            <div class="modal-body">
                <div class="menu_signalr">
                    <a href="@Url.Action("index", "Chat", new { })" target="_blank" class="btn btn-circle-lg btn-danger"><span class="fa fa-weixin"></span></a>
                    <a href="Notify.html" target="_blank" class="btn btn-circle-lg btn-warning"><span class="fa fa-flag"></span></a>
                    <a href="@Url.Action("index", "Cam", new { })" target="_blank" class="btn btn-circle-lg btn-success"><span class="fa fa-camera"></span></a>
                    <a href="@Url.Action("index", "Streaming", new { })" target="_blank" class="btn btn-circle-lg btn-danger"><span class="fa fa-video-camera"></span></a>
                    <a href="@Url.Action("index", "Board", new { })" target="_blank" class="btn btn-circle-lg btn-warning"><span class="fa fa-clipboard"></span></a>
                    <a href="@Url.Action("index", "Luis", new { })" target="_blank" class="btn btn-circle-lg btn-success"><span class="fa fa-connectdevelop"></span></a>
                    <a id="show_info" class="btn btn-circle-lg btn-info"><span class="fa fa-thumbs-up"></span></a>
                </div>
            </div>
            <ul id="info" style="display:none;" class="list-group">
                <li class="list-group-item" style="border-radius: 0;">El chat permite simular un dispositivo conectado para probar envio de mensajes</li>
                <li class="list-group-item" style="border-radius: 0;">Las notificaciones permiten crear notificaciones que se envian a todo los usuarios conectados bajo el perfil que se ingresa (En Construcción)</li>
                <li class="list-group-item" style="border-radius: 0;">La camara permite acceder a las camaras conectadas al dispositivo y tomar fotos (Beta)</li>
            </ul>
        </div>
    </div>
</div>


<script>
    $(document).ready(function () {
        $("#main_Menu").modal("toggle");
    });
    $("#show_info").click(function (evt) {
        $("#info").toggle();
    });
</script>
<style>
    .menu_signalr {
        text-align: center;
    }

    .btn-circle-lg {
        width: 79px;
        height: 79px;
        text-align: center;
        padding: 13px 0;
        font-size: 30px;
        line-height: 2.00;
        border-radius: 70px;
    }
</style>

Chat.Api/Views/Luis/index.cshtml
@{
    ViewBag.Title = "Language Understanding Intelligent Service";
}

<div class="container">
    <div class="row">
        <h1 class="col-xs-12" id="who_is">Language Understanding Intelligent Service</h1>
    </div>

    <input type="hidden" id="displayname" />
    <br />
    <div class="row">
        <div class="col-xs-12 col-lg-12" id="onlineUsers">

        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <input type="text" id="chat-input" placeholder="To chat, type here and press Enter!" class="form-control" />
            <hr />
            <div id="chat-window">

            </div>
        </div>
    </div>
</div>

<script>
    $(function () {

        var params = { "timezoneOffset": "0", "verbose": "false", "spellCheck": "false", "staging": "false", };
        var chatInput = $("#chat-input");
        var chatWindow = $("#chat-window");

        chatInput.keydown(function (e) {

            if (e.which === 13) {
                var message = chatInput.val();


                $.ajax({
                    url: "https://westcentralus.api.cognitive.microsoft.com/luis/v2.0/apps/64a86a46-3bbe-461f-a4a5-dde43b51da96?"+ $.param(params) +"&q=" + message,
                    beforeSend: function (xhrObj) {
                        // Request headers
                        xhrObj.setRequestHeader("Ocp-Apim-Subscription-Key", "fa9a3f6c026e466a8fd2a50aab7a6d4d");
                    },
                    type: "GET",
                    // The request body may be empty for a GET request
                    data: "{body}",
                })
                .done(function (data) {
                    chatWindow.append("<div><strong>intent: </strong>" + data.topScoringIntent.intent + "</div>");

                    chatWindow.append("<div><strong>Query: </strong>" + data.query + "</div>");

                    data.entities.forEach(f =>  chatWindow.append("<div><strong>Entidad: </strong>" + f.entity + "</div>"))

                    //empty the textbox
                    chatInput.val("");

                    //focus cursor on the textbox for easy chatting!
                    self.focus();
                })
                .fail(function () {
                    alert("error");
                });
            }
        });


    });
</script>

Chat.Api/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/css/Site.css" rel="stylesheet" />

    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/jquery.signalR-2.2.2.js"></script>
    <script src="../signalr/hubs"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>
</body>
</html>

Chat.Api/Views/Streaming/Index.cshtml
<script src="~/Scripts/Streaming.js"></script>

<div class="panel panel-default">
    <div class="panel-body">
        <div class="col-md-12" id="videoStream">
            <div class="row">
                <div style="margin: auto;width: 30%;">
                    <div class="form-group">
                        <button class="btn btn-success btn-block" id="startBtn" disabled="disabled">Start Call</button>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <video autoplay class="video mine" id="rtcVideo"></video>
                </div>
            </div>
        </div>
    </div>
</div>